[build]
  publish = "renomeador-nf-gdm-app/build"
  command = "cd renomeador-nf-gdm-app && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.1"